FROM docker.io/archlinux:base-devel
    MAINTAINER xz <xiangzhedev@gmail.com>

COPY 10-pacclean.hook /etc/pacman.d/hooks/10-pacclean.hook

RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm wget unzip

RUN wget https://github.com/phoronix-test-suite/phoronix-test-suite/archive/refs/heads/master.zip -O /tmp/phoronix-test-suite.zip && \
    unzip /tmp/phoronix-test-suite.zip -d /tmp/ && \
    mv /tmp/phoronix-test-suite-master /phoronix-test-suite && \
    cd /phoronix-test-suite && \
    ./install-sh && \
    cd / && \
    rm -rf /tmp/*

RUN pacman -S --noconfirm php

# Due network is slow, easier to retry
{{INSTALL_COMMANDS}}

COPY phoronix-test-suite.xml /etc/phoronix-test-suite.xml
RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm blender
# Default run time but no DynamicRunCount
#ENV FORCE_TIMES_TO_RUN=3

RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm libpfm devtools perf llvm

RUN wget https://github.com/google/autofdo/releases/download/v0.30.1/create_llvm_prof-x86_64-v0.30.1.zip -O /tmp/create_llvm_prof-x86_64-v0.30.1.zip && \
    unzip /tmp/create_llvm_prof-x86_64-v0.30.1.zip -d /usr/bin/ && \
    chmod +x /usr/bin/create_llvm_prof && \
    rm -rf /tmp/*

RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm time

COPY build.py /usr/bin/build.py
RUN chmod +x /usr/bin/build.py

WORKDIR /

ENTRYPOINT ["/usr/bin/build.py"]
